# Generated by Django 4.0.5 on 2022-06-06 10:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherProfile',
            new_name='StudentProfile',
        ),
    ]
