# Generated by Django 4.0.5 on 2022-06-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_rename_teacherprofile_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
