# Generated by Django 4.0.5 on 2022-06-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_studentprofile_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
