# Generated by Django 4.0.5 on 2022-06-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addiction', models.CharField(blank=True, max_length=100, null=True)),
                ('phobia', models.CharField(blank=True, max_length=100, null=True)),
                ('illness', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment', models.CharField(blank=True, max_length=200, null=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentHobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(blank=True, max_length=70, null=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExtraCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(blank=True, max_length=100, null=True)),
                ('achievements', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rollNo', models.IntegerField(null=True, unique=True)),
                ('AimForLife', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_of_engg', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('Course', models.CharField(blank=True, max_length=50, null=True)),
                ('YearOfAdmission', models.IntegerField(null=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conct_no', models.IntegerField(blank=True, null=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GuardianDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('relationshipWithStudent', models.CharField(blank=True, max_length=50, null=True)),
                ('motherHighestEducation', models.CharField(blank=True, max_length=50, null=True)),
                ('fatherHighestEducation', models.CharField(blank=True, max_length=50, null=True)),
                ('motherOccupation', models.CharField(blank=True, max_length=50, null=True)),
                ('fatherOccupation', models.CharField(blank=True, max_length=50, null=True)),
                ('yearlyIncome', models.IntegerField(blank=True, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(max_length=50, null=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentprofile')),
            ],
        ),
    ]
