# Generated by Django 4.0.5 on 2022-06-16 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addiction', models.CharField(blank=True, max_length=100, null=True)),
                ('phobia', models.CharField(blank=True, max_length=100, null=True)),
                ('illness', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment', models.CharField(blank=True, max_length=200, null=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExtraCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(blank=True, max_length=100, null=True)),
                ('achievements', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentprofile')),
            ],
        ),
    ]
