# Generated by Django 4.0.5 on 2022-06-08 04:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_studentprofile_blood_grp_studentprofile_branch_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mentors',
            new_name='MentorProfile',
        ),
    ]
