# Generated by Django 4.0.4 on 2022-06-02 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, null=True)),
                ('course', models.CharField(max_length=20, null=True)),
                ('YearOfAdmission', models.IntegerField(max_length=4, null=True)),
                ('current_RollNo', models.IntegerField(max_length=3, null=True)),
                ('AimForLife', models.CharField(max_length=250, null=True)),
                ('Reason_of_eng', models.CharField(max_length=20, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
